<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\CoinFlow.Domain\CoinFlow.Domain.csproj" />
    <ProjectReference Include="..\CoinFlow.Application\CoinFlow.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="PdfPig" Version="0.1.16" />
    <PackageReference Include="sqlite-net-pcl" Version="1.9.172" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoWarn>$(NoWarn);NETSDK1206</NoWarn>
  </PropertyGroup>

</Project>
